
debug_mode: True

# visible video precentage
video_per: .3
num_latents: 256
dataset:  smthng-smthng_sub21
precision: mixed
data_dir: ./data/20bn-something-something-v1_fine/
label_dir: ./labels/ssv1/sub21

# GPU-device related parser arguments & number of workers
workers: 8

# set batch size
batch_size: 64
frame_size: [100, 176]
